<template>
  <v-form
    @submit.prevent="submit"
    class="form"
  >
    <v-text-field
      v-model="name.value.value"
      :error-messages="name.errorMessage.value"
      label="Name"
      variant="solo-inverted"
    ></v-text-field>

    <v-text-field
      v-model="phone.value.value"
      :error-messages="phone.errorMessage.value"
      label="Phone Number"
      variant="solo-inverted"
    ></v-text-field>

    <v-text-field
      v-model="email.value.value"
      :error-messages="email.errorMessage.value"
      label="E-mail"
      variant="solo-inverted"
    ></v-text-field>

    <v-rating
      v-model="rating.value.value"
      ref="ratingElement"
      class="rating"
      :class="{ 'show-error': displayRatingError }"
      label="Rating"
      :model-value="defaultRatingValue"
      :length="5"
      :size="50"
      hover
      active-color="primary"
      @click.stop="handleRate"
    ></v-rating>

    <v-textarea
      v-model="comment.value.value"
      label="Comment"
      variant="solo-inverted"
      :model-value="defaultCommentValue"
    >
    </v-textarea>

    <v-btn class="me-4" type="submit"> submit </v-btn>

    <v-btn @click="handleReset"> clear </v-btn>
  </v-form>
</template>

<script setup>
  import { ref, toRefs, computed } from 'vue'
  import { useField, useForm } from 'vee-validate'

  import { collection, addDoc } from 'firebase/firestore'
  import { db } from '@/firebase'

  const ratingElement = ref(null)
  const isRated = ref(false)
  const displayRatingError = ref(false);
  const defaultRatingValue = computed(() => {
    return rating.value.value || 3; // Set the default value here as needed
  });
  const defaultCommentValue = computed(() => {
    return comment.value.value || ''; // Set the default value here as needed
  });

  const props = defineProps({ feedbackData: Array, required: true , formSubmitted: Boolean, required: true })
  const { feedbackData, formSubmitted } = toRefs(props)

  const emit = defineEmits(['formSubmittedToTrue']); // Define the 'setToSubmitted' event
  const formSubmittedToTrueRun = () => {
    emit('formSubmittedToTrue')
  }

  const handleRate = () => {
    isRated.value = true
    displayRatingError.value = false
  }

  const { handleSubmit, handleReset } = useForm({
    validationSchema: {
      name(value) {
        if (value?.length >= 2) return true

        return 'Name needs to be at least 2 characters.'
      },
      phone(value) {
        // Check if the phone number already exists in feedbackData
        if (Array.from(feedbackData.value).some(item => item.phone === value)) {
          return 'Phone number already exists in Database.';
        }

        if (/^\+\d{12}$/.test(value)) {
          return true;
        } else {
          return 'Phone number needs to be like this +380997774422.';
        }
      },
      email(value) {
        // Check if the email already exists in feedbackData
        if (Array.from(feedbackData.value).some(item => item.email === value)) {
          return 'Email already exists in Database.';
        }
        // Perform email validation
        if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(value)) {
          return true;
        } else {
          return 'Email should be valid, e.g. mail.example@gmail.com';
        }
      },
      rating(value) {
        return true;
      },
      comment(value) {
        return true;
      }
    },
  })

  const name = useField('name')
  const phone = useField('phone')
  const email = useField('email')
  const rating = useField('rating')
  const comment = useField('comment')

  const submit = handleSubmit(async(values) => {
    if (!isRated.value) {
      displayRatingError.value = !isRated.value
      return;
    }

    const formObject = { ...values }
    console.log(JSON.stringify(formObject, null, 2))
    // Add a new document in collection "cities"
    const docRef = await addDoc(collection(db, "feedbacks"), formObject);
    console.log('ID autogenerated by Firebase:', docRef.id)

    // Emit the 'submitted' event
    formSubmittedToTrueRun()
    handleReset()
    console.log('emits.submitted()')
  });
</script>

<style>
.form {
  min-width: 35dvw;
  height: 50vmin !important;
}

.rating {
  position: relative;
  bottom: 0.25rem;
}

.rating.show-error::after {
  position: absolute;
  bottom: -0.5rem;
  content: 'Please rate our service(-s)';
  width: 100%;
  font-size: 12px;
  font-weight: 400;
  color: #bd5e6d;
}
</style>